"""Core domain models, enums, validation, ratings, valuation, and serialization.

The :mod:`core` package contains no UI and no I/O: it is a pure, deterministic
model of the football world. Everything in the game is built on these types.
"""

from manager.core.enums import (
    AttackingApproach,
    CompetitionType,
    DefensiveApproach,
    DefensiveLine,
    Difficulty,
    FixtureStatus,
    MatchEventType,
    NewsCategory,
    PassingStyle,
    PersonalityTrait,
    PlayingStyle,
    Position,
    PressingIntensity,
    Tempo,
    TransferStatus,
    TransferType,
)
from manager.core.models import (
    BoardConfidence,
    CareerState,
    Club,
    ClubFinances,
    ClubObjective,
    Competition,
    Contract,
    DevelopmentRecord,
    Fixture,
    Injury,
    Manager,
    MatchEvent,
    MatchStats,
    NewsArticle,
    Player,
    PlayerSeasonStats,
    Season,
    SquadSelection,
    Standings,
    Suspension,
    Tactics,
    Transfer,
)
from manager.core.ratings import overall_rating, position_weights
from manager.core.serialization import dump, load
from manager.core.validate import ValidationError

__all__ = [
    "AttackingApproach",
    "BoardConfidence",
    "CareerState",
    "Club",
    "ClubFinances",
    "ClubObjective",
    "Competition",
    "CompetitionType",
    "Contract",
    "DefensiveApproach",
    "DefensiveLine",
    "DevelopmentRecord",
    "Difficulty",
    "Fixture",
    "FixtureStatus",
    "Injury",
    "Manager",
    "MatchEvent",
    "MatchEventType",
    "MatchStats",
    "NewsArticle",
    "NewsCategory",
    "PassingStyle",
    "PersonalityTrait",
    "Player",
    "PlayerSeasonStats",
    "PlayingStyle",
    "Position",
    "PressingIntensity",
    "Season",
    "SquadSelection",
    "Standings",
    "Suspension",
    "Tactics",
    "Tempo",
    "Transfer",
    "TransferStatus",
    "TransferType",
    "ValidationError",
    "dump",
    "load",
    "overall_rating",
    "position_weights",
]